language: node_js
node_js:
  - "15"
script:
  - echo 'Build starts..'
  - echo 'Installing Dependencies..'
  - npm install
  - echo 'Testing..'
  - npm test
deploy:
  provider: heroku
  api_key: 6+aG7x3099oARXepaRPv1bB5VL7oT40axTb75VXuW+75t7MZ0yX3ji38YFAU2reytGy7SN0Lct7+OdaMxd68wtOZ2Nyqcp8malnKJULJ9jz7JJECn/x1nLBFnVeCykd0Qhxz9KO21ElEYMe/FEAgnYQ2t2J+4csDP8SIc7VqpD1mBKoKhsPaAY70S07BdzktImOah+nbQ2kAFpqAsuxbhW7eD7rBk5pe2tXs7cHmVy4g0vjmz9uwu4mgAERzm+PNMScj/1Ctt26WoSYQkpTgV4Vrb3BE+uf3gr/ZN8ub+DAS82njlefWmfy2QIHj5ypsvuf5u+wOd8bTEEj6roUmMU7UfjM7L0zzIuUOoOXqyiJ8je3P+vgKn8l/LFphKAAQp0vCPxA3LSy328ns5wTAeZKSf+dmMfZxG8ITeRSX8vi1eDOXc2IJ3rpyjopo0A8RcrHmgKEbFCrU+om1F6Zoh3I9FaJr2FyoYwdqTRes+GwFnp8HhvcZt2SjDg4yNy8YabX202KdL5gAltvj8QwIuwwIdqCG84D5AqN+lZdis6E14YosoLjxOydFlI8LKuWXWo5paKl0ZtmXUuvwadL29E9/hqz9TQOw8qUkyernl2n0bM4WdZ0BNWpp/5pduLpKWPFx0hl/F3R122x+ppYvDXkJu8+Gv/a2t/rvSIHOfMc=
  on:
    branch: main
